--- 
- 
  connection: local
  gather_facts: false
  hosts: LAB_all
  roles:
    - Juniper.junos
  name: "Retrieve configuration from Junos devices"
  tasks:
    - 
      file: 
        path: "Configuraciones/{{ inventory_hostname }}"
        state: directory
      name: "creacion de directorio para cada Nodo" 
    - 
      junos_get_config:
#        provider: "{{ credentials }}"
        host: "{{junos_host}}"
        user: "{{ADMUSER}}"
        passwd: "{{ADMPASS}}"
        dest: "Configuraciones/{{inventory_hostname}}/{{inventory_hostname}}_all.conf"
        format: text
      name: "Retrieve configuration from Junos devices"
#      logfile: {{playbook_dir}}/junos_get_config.log
#      filter=system
