---
- name: Change configuration using junos_config module
  hosts: MX80_01
  connection: local
  gather_facts: no
  vars_files:
  - "vlans.yml"
  
  tasks:

  - name: create vlans
    tags: configuration
    junos_config:
      lines:
        - "set vlans {{ item.name }} vlan-id {{ item.id }}"
      comment: "create vlans from Ansible"
      provider: "{{ credentials }}"
      timeout: 300
    with_items: "{{ vlans }}"

#    junos_command:
#      provider: "{{  credentials }}"
#      commands:
#       - show vlans {{item.name}}
#      waitfor:
#       - "result[0].vlan-information.vlan.vlan-name eq {{item.name }} "
#    with_items: "{{ vlans }}"
    
