---
- name: Configuration using Jinja2 file
  hosts: MX80
  connection: local
  gather_facts: no
  tasks: 
    - 
      file: 
        path: "Configuraciones/{{ inventory_hostname }}"
        state: directory
      name: "creacion de directorio para cada Nodo"
    -  
      template:
        src: Interfaces.j2
        dest: Configuraciones/{{inventory_hostname}}/{{inventory_hostname}}_interfaces.conf
      name: "Archivos de Configuracion"
    -
#      name: Aplicar configuracion
#      junos_config:
#        provider: "{{ credentials }}"
#        timeout: 300
#        src: Configuraciones/{{inventory_hostname}}/{{inventory_hostname}}_L2PtP.conf
#        src_format: set