--- 
- 
  connection: local
  gather_facts: false
  hosts: MX80_11
  name: "Show Route"
  roles: 
    - Juniper.junos
  tasks: 
    - 
      juniper_junos_command: 
        host: "{{junos_host}}"
        user: "{{USERNAME}}"
        passwd: "{{DEVICE_PASSWORD}}"
        command: show route
      name: "Get Device Routes"
      register: junos
    - 
#      debug: msg="{{junos.facts.version}}" version 1.0.3  Modulo Juniper
      debug:
        var: junos
      name: "Print Routes"
  vars_prompt: 
    - 
      name: USERNAME
      private: false
      prompt: "User name"
    - 
      name: DEVICE_PASSWORD
      private: true
      prompt: "Device Password"
