--- 
- 
  connection: local
  gather_facts: false
  hosts: MX80_01
  name: PING
  roles: 
    - Juniper.junos
  tasks: 
    - 
      juniper_junos_ping: 
        dest: "10.10.10.10"
      name: "Ping 10.10.10.1 with default parameters. Fails if any packets lost."
  vars_prompt: 
    - 
      name: USERNAME
      private: false
      prompt: "User name"
    - 
      name: DEVICE_PASSWORD
      private: true
      prompt: "Device Password"